// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivbyonxkweplhcipvbhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2Ynlvbnhrd2VwbGhjaXB2YmhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NDc0OTgsImV4cCI6MjA2MjEyMzQ5OH0.fVFYVaxljvHUsBER4bvL-5OJrR9FZLDGbHVhXYqXeI0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);